# Generated by Django 2.2.14 on 2020-07-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='cghsgfhwsh',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
