# Generated by Django 2.2.14 on 2020-07-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_customtext_cghsgfhwsh"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="jhgjgj",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
