# Generated by Django 2.2.14 on 2020-07-21 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customtext_jhgjgj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='cghsgfhwsh',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='jhgjgj',
        ),
    ]
