# Generated by Django 2.2.14 on 2020-07-21 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_homepage_uytuytuy"),
    ]

    operations = [
        migrations.RemoveField(model_name="homepage", name="uytuytuy",),
    ]
