# Generated by Django 2.2.14 on 2020-07-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_homepage_uytuytuy'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='jhgjhgjh',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='uytuytuy',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
