# Generated by Django 2.2.14 on 2020-07-21 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200721_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='jhgjhgjh',
            new_name='jhgjhgjhgjhgjhjg',
        ),
    ]
